version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_DIR: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: ["python", "app.py"]
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_DIR: frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    command: [
      "streamlit", "run", "app.py",
      "--server.port=8501",
      "--server.address=0.0.0.0"
    ]
    restart: unless-stopped